import pool from '../db';

const runners = [
  { name: 'Joe McConaughy', bib_number: 65 },
  { name: 'Conner Engelking', bib_number: 27 },
  { name: 'Cameron Johnson', bib_number: 46 },
  { name: 'Edward Murphy', bib_number: 72 },
  { name: 'Yassine Diboun', bib_number: 18 },
  { name: 'John Lofthus', bib_number: 57 },
  { name: 'Brandon Sturges', bib_number: 99 },
  { name: 'Harley Le Leivre', bib_number: 54 },
  { name: 'Greg Friedman', bib_number: 30 },
  { name: 'Brandon Rittenour', bib_number: 86 },
  { name: 'Skeets Morel', bib_number: 71 },
  { name: 'Mickey Cotter', bib_number: 14 },
  { name: 'Brett Burnside', bib_number: 10 },
  { name: 'Patrick Baylis', bib_number: 3 },
  { name: 'Richard Crabtree', bib_number: 15 },
  { name: 'Seth Brody', bib_number: 7 },
  { name: 'Bret Jorgensen', bib_number: 47 },
  { name: 'Christopher Barry', bib_number: 1 },
  { name: 'Nolan Uhlich', bib_number: 102 },
  { name: 'Jon Dukes', bib_number: 22 },
  { name: 'Chantelle Malmoe', bib_number: 61 },
  { name: 'Vince Molosky', bib_number: 68 },
  { name: 'Simon Carn', bib_number: 11 },
  { name: 'Frederick Green', bib_number: 35 },
  { name: 'Ksusha Shambarger', bib_number: 92 },
  { name: 'Kirk Wojcik', bib_number: 114 },
  { name: 'Ryan Wisler', bib_number: 112 },
  { name: 'Julija Soryte', bib_number: 97 },
  { name: 'Scott Palmer', bib_number: 78 },
  { name: 'Wendelin Macht', bib_number: 60 },
  { name: 'Stewart Gray', bib_number: 34 },
  { name: 'Gavin Woody', bib_number: 117 },
  { name: 'Scott Davis', bib_number: 16 },
  { name: 'Nick Eldridge', bib_number: 25 },
  { name: 'Gabriel Huau', bib_number: 45 },
  { name: 'Sam Kanner', bib_number: 48 },
  { name: 'Ryan Burns', bib_number: 9 },
  { name: 'Robert Shearer', bib_number: 93 },
  { name: 'Simeon Gilmer', bib_number: 33 },
  { name: 'Stephanie Christau', bib_number: 13 },
  { name: 'Mark Giangiordano', bib_number: 32 },
  { name: 'Janay Geiser', bib_number: 31 },
  { name: 'Tyler Park', bib_number: 79 },
  { name: 'Erin Lavoie', bib_number: 53 },
  { name: 'Jhett Reyes', bib_number: 85 },
  { name: 'Brian Hillis', bib_number: 42 },
  { name: 'Jade Lenning', bib_number: 55 },
  { name: 'Carshena Harvin', bib_number: 39 },
  { name: 'Christina Bonnyman', bib_number: 6 },
  { name: 'Hayley Dukatz', bib_number: 21 },
  { name: 'Connor Fredrickson', bib_number: 29 },
  { name: 'Matt Hagen', bib_number: 37 },
  { name: 'Maddy Watkins', bib_number: 110 },
  { name: 'Kim Slate', bib_number: 96 },
  { name: 'Craig Engelking', bib_number: 28 },
  { name: 'Pete McHugh', bib_number: 67 },
  { name: 'Alexander Schwarzkopf', bib_number: 91 },
  { name: 'Brook Burke', bib_number: 8 },
  { name: 'Mark Vennerholm', bib_number: 106 },
  { name: 'Lynn Dougherty', bib_number: 20 },
  { name: 'Kimberly Pearce', bib_number: 80 },
  { name: 'John Kubinak', bib_number: 51 },
  { name: 'Stefanie Bernosky', bib_number: 4 },
  { name: 'Chassen Ortiz', bib_number: 76 },
  { name: 'James Picker', bib_number: 82 },
  { name: 'Kelly O\'Callahan', bib_number: 75 },
  { name: 'David Mcburney', bib_number: 64 },
  { name: 'Ellen Hostetler', bib_number: 44 },
  { name: 'Weston Ruhlman', bib_number: 89 },
  { name: 'Alexander Yukhanov', bib_number: 118 },
  { name: 'Glen Mangiantini', bib_number: 62 },
  { name: 'Paul Ward', bib_number: 109 },
  { name: 'James Lewis', bib_number: 56 },
  { name: 'Stephanie Decker', bib_number: 17 },
  { name: 'Johannes Moolman', bib_number: 69 },
  { name: 'Barry Bingham', bib_number: 5 },
  { name: 'Jim Martinson', bib_number: 63 },
  { name: 'Max Hepp-Buchanan', bib_number: 40 },
  { name: 'Devon Varmega', bib_number: 104 },
  { name: 'Shiqiang Su', bib_number: 100 },
  { name: 'Brandon Ott', bib_number: 77 },
  { name: 'Taylor Woodcock', bib_number: 116 },
  { name: 'Daniel Murray', bib_number: 73 },
  { name: 'Monica Batchelor', bib_number: 2 },
  { name: 'Gunjan Sethi', bib_number: 0 },
  { name: 'Jason Verlinde', bib_number: 107 },
  { name: 'Evan Simpson', bib_number: 94 },
  { name: 'Allen Horesh', bib_number: 43 },
  { name: 'Ben Hildner', bib_number: 41 },
  { name: 'Genevieve Pfeiffer', bib_number: 81 },
  { name: 'Carter Eck', bib_number: 24 },
  { name: 'Andrew Grillos', bib_number: 36 },
  { name: 'David Rabeshko', bib_number: 83 },
  { name: 'Ste Elmore', bib_number: 26 },
  { name: 'Scott Williams', bib_number: 111 },
  { name: 'Brittyn Nicholson', bib_number: 74 },
  { name: 'Michael Moree', bib_number: 70 },
  { name: 'Makena Rutledge', bib_number: 90 },
  { name: 'Jonathan Rosenblatt', bib_number: 88 },
  { name: 'Joe Hanson Vazquez', bib_number: 38 },
  { name: 'Ben Kulbago', bib_number: 52 },
  { name: 'Bryan Kirk', bib_number: 50 },
  { name: 'Kailey Doran', bib_number: 19 },
  { name: 'Jordan Rosas', bib_number: 87 },
  { name: 'Danstan Kaunda', bib_number: 49 },
  { name: 'Jacob Zalud', bib_number: 119 },
  { name: 'Geoff McDonald', bib_number: 66 },
  { name: 'Chauncey Red Crow', bib_number: 84 },
  { name: 'Liam Simpson', bib_number: 95 },
  { name: 'Quinten Velthuijzen', bib_number: 105 },
  { name: 'Isaac Strom', bib_number: 98 },
  { name: 'Jake Tveite', bib_number: 101 },
  { name: 'Justin Dunham', bib_number: 23 },
  { name: 'Steve Chan', bib_number: 12 },
  { name: 'Selvakumar Vairasamy', bib_number: 103 },
  { name: 'Jared Virani', bib_number: 108 },
  { name: 'Johanna M Sherman', bib_number: 59 },
  { name: 'Johannah Ludwig', bib_number: 58 },
  { name: 'Thor Woelfel', bib_number: 113 },
];

async function seedRunners() {
  const raceResult = await pool.query('SELECT id FROM race LIMIT 1');
  const race_id = raceResult.rows[0].id;

  for (const runner of runners) {
    if (runner.bib_number === 0) continue;
    await pool.query(
      'INSERT INTO runner (name, bib_number, race_id, status) VALUES ($1, $2, $3, $4) ON CONFLICT (bib_number) DO NOTHING',
      [runner.name, runner.bib_number, race_id, 'active']
    );
  }
  
  console.log('Runners seeded successfully');
  process.exit(0);
}

seedRunners().catch(console.error);