POST http://localhost:8080/runners
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Im1vbSIsImlkIjoxLCJpYXQiOjE3ODM4MjIxNTUsImV4cCI6MTc4MzkwODU1NX0.AsAcKSL7AucJBQsHG3yqrcdiTkjLUQhoQtqxk274HM0
Content-Type: application/json

{
  "name": "Tommy",
  "age": 56,
  "bib_number": 333,
  "emergency_contact_name": "Nicole",
  "emergency_contact-number": "890-000",
  "race_id": 1

}